### ISSUE TITLE
HTTPS failed

### ISSUE THREAD

**Issue by anemol** [Lesterpig/sockpress#11]
With HTTP,  httpserver and sockpress work.

But with HTTPS, only httpserver works, sockpress can't connect.

Here my code:
```javascript
var isHTTPS=true;
var options;
if (isHTTPS)
{
  options =
  {
      secret: secret_key,
      resave: true,
      saveUninitialized: false,
  	https:
  	{
          key: fs.readFileSync(__dirname+'/credentials/key.pem'),
          cert: fs.readFileSync(__dirname+'/credentials/cert.pem')
      }
  };
}
else
{
  options =
  {
      secret: secret_key,
      resave: true,
      saveUninitialized: false,
  };
}
var app = require("sockpress").init(options);

..
	if (isHTTPS)
	{
  	
  		https.createServer({  key: fs.readFileSync(__dirname+'/credentials/key.pem'),  cert: fs.readFileSync(__dirname+'/credentials/cert.pem')}, app).listen(5000);
  	
	}
	else
	{
	    app.listen(5000, "127.0.0.1");
	}
```

client side:
```javascript
	if (isHTTPS)
			socket = io.connect('https://' + document.domain + ':' + location.port + '/', {secure: true});
		else
			socket = io.connect('http://' + document.domain + ':' + location.port + '/');
```

**Comment by Lesterpig** [comment]
Hi! Sockpress' https feature is tested under several versions of node and should work, but I'll check that as soon as possible.

In the meantime, could you give me your system information? (OS, Node.js and NPM versions)
Any error message can also be useful.

**Comment by anemol** [comment]
Kubuntu 15.10 
NodeJS v5.9.0 / npm@3.7.3

Modules:
├── async@1.5.2 
├── async-waterfall@0.1.5 
├── body-parser@1.15.0 
├── connect-pg-simple@3.1.0 
├── crypto@0.0.3 
├── ejs@2.4.1 
├── ent@2.2.0 
├── fs@0.0.2 
├── glob@7.0.3 
├── https@1.0.0 
├── locks@0.2.2 
├── node-uuid@1.4.7 
├── nodemailer@2.3.0 
├── passport@0.3.2 
├── passport-local@1.0.0 
├── path@0.12.7 
├── pg@4.5.1 
├── require-reload@0.2.2 
├─┬ sockpress@1.0.2 
│ ├── cookie@0.2.3 
│ └─┬ express@4.13.4
│   └── cookie@0.1.5 
├── tls@0.0.1 
├── util@0.10.3 
├── wallet-address-validator@0.1.0 
├── winston@2.2.0 
└── zmq@2.14.0 

Client side:
tested with socket.io-1.3.7 & socket.io-1.4.5

**Comment by anemol** [comment]
GET /socket.io/?EIO=3&transport=polling&t=LFBtvqn HTTP/1.1
Host: localhost:5000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Referer: https://localhost:5000/
Cookie: io=SflD54ukYllHBh1CAAAA; sockpress.id=s%3A_TMun9QjRaNh7hBEFf0TCekc_w6DY1X6.%2BQdapgAm6ofwDtTVFogVLZ1fo%2B2oG8yhDKgfGYBOn50; PPA_ID=cuf1d55nm08jomoeaclsc75335; webfx-tree-cookie-persistence=wfxt-18+wfxt-16+wfxt-10+wfxt-6+wfxt-4+wfxt-20
Connection: keep-alive

HTTP/1.1 404 Not Found
X-Powered-By: Express
x-content-type-options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 65
Date: Thu, 31 Mar 2016 08:52:22 GMT
Connection: keep-alive

**Comment by Lesterpig** [comment]
Ok, I investigated around the https feature, and it seems that everything works as intended. However, I probably just found an issue in your code.

```javascript
if (isHTTPS)
{
  https.createServer({  key: fs.readFileSync(__dirname+'/credentials/key.pem'),  cert: fs.readFileSync(__dirname+'/credentials/cert.pem')}, app).listen(5000);
}
else
{
  app.listen(5000, "127.0.0.1");
}
```

When using https, you are not using the sockpress `listen` method, that will handles the http**s** switch for you if you provide the `https` option during the initialization (it is the case in your example).

Just replace the above code by `app.listen(5000, "127.0.0.1");`, and let me know if it fixes your issue :grinning:

**Comment by anemol** [comment]
Fine! It fixes my issue ! :)

Thank you very much.

I already have a site that works with socketpress for several months but using only HTTP. I'm currently doing a new site but will use HTTPS. Socketpress is very simple to use.

**Comment by Lesterpig** [comment]
You're welcome! Please report any other issues you may encounter using sockpress, it would be greatly appreciated ;)
