### ISSUE TITLE
Room doesn't work

### ISSUE THREAD

**Issue by anemol** [Lesterpig/sockpress#18]
I have 2 servers who use sockpress
- a  main website 
- a  game server (on an other port)

I use Nginx as front proxy.

For the main website, i can use room without problem (join, broadcast to room)

For the game server, rooms don't work.

The main website provides the HTML/javacript and then, the javascript connects to the game server (socketio).

It works well since a while. But, recently, i wanted to use the room feature  and i realized that it didn't work.  There is no error. 

```
app.io.route("/","ready", function( socket,version)
{
 ...
   socket.emit("preparing",data);
   socket.join("gaming");
});

setInterval(function()
{
	if (app && app.io)
	{
          app.io.in('gaming').emit("debugmessage","Hello gaming room!!!");
        }
}
},1000);
```

The debug message is never received on the client side.

Any idea?

**Comment by Lesterpig** [comment]
There is a test for the room feature (https://github.com/Lesterpig/sockpress/blob/master/test/scripts/http.js#L89). However, there may be a bug with the namespace system.

Can you try replacing `app.io.route("/","ready", function( socket,version)` with `app.io.route("ready", function( socket,version)`?

Alternatively, it may be a misuse of the `ready` event. You can also try to change the event name.

If nothing work, I'll investiguate.

**Comment by anemol** [comment]
I applied the modifications but no change.

Finally, i found the source of my problem. To authenticate users, i check the validity of a simple token (given by the authoritative webserver) and i initialize a variable socket.id=token
I renamed to "myId" instead "id" and now, it works

Anyway, thanks for your answer. :)

**Comment by stevokk** [comment]
Can you share the contents of ioRoute & where you are calling joinRoom from and what values are being passed for room (is it '/' & '/product')?

**Comment by andreddosantos** [comment]
Just commited my code here!
https://gogs.cosmosmade.com/adosantos/MoscaSockpress

**Comment by stevokk** [comment]
I'll look into the code now as it has been a few years.. I'd suggest quickly logging the room and socket values in the joinRoom function to make sure it is passing the same values when it's mounted on the two different routes. From a first glance I can't see why the route namespaces would affect your custom room joining.

**Comment by andreddosantos** [comment]
Yup it seems so :/ 

"Rooms
Within each namespace, you can also define arbitrary channels that sockets can join and leave."

https://socket.io/docs/rooms-and-namespaces/

my bad ;)

**Comment by stevokk** [comment]
Have you resolved your issue? One thought is to check your client side connection, and that you're setting the correct namespace to connect to on the server.

**Comment by andreddosantos** [comment]
I was able to get it to work by providing the namespace where there room is located.

` app.io.of('/product').to(client.id).emit(.... `

But according to the socketio documentation (rooms are inside namespaces), so this is not a bug, i believe
