### ISSUE TITLE
Feature request: set socket.io init attribute serveClient

### ISSUE THREAD

**Issue by firig** [Lesterpig/sockpress#20]
When compiling SockPress with **WebPack** (relevant in the context of Angular Universal), you get errors regarding unresolved references to socket.io-client.  
If you were using socket.io directly, these errors could be avoided by setting an init option: {serveClient: false}. However, since SockPress handles socket.io for you, you cannot yourself give this option. And the way options to SockPress are handled, you cannot use those to set serveClient for socket.io.
Request: please allow a mechanism to tell SockPress to forward the serveClient attribute to socket.io

Ps, when directly patching SockPress, the wanted functionality can be achieved by substituting line 47 in lib.index.js with:
`_app.io = io(_server, {serveClient: false});`

**Comment by Lesterpig** [comment]
Fixed by v1.4.0 (use `options.io`)
