### ISSUE TITLE
socket.io v2.2

### ISSUE THREAD

**Issue by anemol** [Lesterpig/sockpress#23]
I want to use the v2.2.0 of socket.io on the client side, so to be consistent, it is also necessary that the server runs with the same version with sockpress.

How to make sockpress use the right version?

**Comment by Lesterpig** [comment]
Hi, thanks for your interest! You may just need to update the `socket.io` package within `sockpress` directory.

Two options: `yarn add socket.io@2.2.0` or `npm install socket.io@2.2.0`.

**Comment by anemol** [comment]
I will try.

I updated the package.json for socket.io  and updated the other packages too (express, etc)

```
 "dependencies": {
    "cookie": "^0.2.3",
    "cookie-parser": "^1.4.1",
    "express": "^4.16.4",
    "express-session": "^1.13.0",
    "socket.io": "^2.2.0"
  },
```
